name: Required Approvals

on:
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  checks: write
  pull-requests: read

jobs:
  required-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check if source branch contains "safety"
        id: check-branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == *safety* ]]; then
            echo "apply-approval-requirements=true" >> $GITHUB_ENV
          else
            echo "apply-approval-requirements=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}

      - name: Get Pull Request Approvals
        id: get-approvals
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            // Get unique approvals
            const approvedReviews = new Set(
              reviews.filter(review => review.state === 'APPROVED').map(review => review.user.login)
            );

            core.setOutput('approvals', approvedReviews.size);
          result-encoding: string

      - name: Check Approval Requirements
        if: env.apply-approval-requirements == 'true'
        run: |
          APPROVALS=${{ steps.get-approvals.outputs.approvals }}
          echo "Number of approvals: $APPROVALS"
          if [[ $APPROVALS -lt 2 ]]; then
            echo "❌ Not enough approvals. At least 2 are required."
            exit 1
          else
            echo "✅ Approval requirements met."
          fi

      - name: Skip approvals for non-safety branches
        if: env.apply-approval-requirements != 'true'
        run: echo "No approval requirements applied for this branch."
