name: Enforce Review Conditions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch contains 'safety'
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }} | grep -i 'safety' || true)
          if [ -n "$BRANCH_NAME" ]; then
            echo "Branch contains 'safety', setting 2 reviews required."
            echo "TWO_REVIEWS_REQUIRED=true" >> $GITHUB_ENV
          else
            echo "Branch does not contain 'safety', setting 1 review required."
            echo "TWO_REVIEWS_REQUIRED=false" >> $GITHUB_ENV
          fi

      - name: Set Status Check for 2 reviews
        if: env.TWO_REVIEWS_REQUIRED == 'true'
        uses: peter-evans/status-check@v1
        with:
          context: "Required Review Count"
          state: failure
          description: "2 reviews are required"

      - name: Set Status Check for 1 review
        if: env.TWO_REVIEWS_REQUIRED != 'true'
        uses: peter-evans/status-check@v1
        with:
          context: "Required Review Count"
          state: success
          description: "1 review is required"
