name: Enforce Review Conditions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if branch contains 'safety'
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }} | grep -i 'safety' || true)
          if [ -n "$BRANCH_NAME" ]; then
            echo "Branch contains 'safety', setting 2 reviews required."
            echo "2-reviews-required=true" >> $GITHUB_ENV
          else
            echo "Branch does not contain 'safety', setting 1 review required."
            echo "2-reviews-required=false" >> $GITHUB_ENV
          fi

      - name: Set Status Check
        uses: peter-evans/status-check@v1
        with:
          context: "Required Review Count"
          state: ${{ env.2-reviews-required == 'true' && 'failure' || 'success' }}
          description: |
            ${{ env.2-reviews-required == 'true' && '2 reviews are required' || '1 review is required' }}
